### ISSUE TITLE
Disaster recovery - back-up for Heroku databases

### ISSUE THREAD

**Issue by MichaelHanksSF** [SocialFinanceDigitalLabs/cs-demand-model-regional#126]
Our SLAs dictate that we need to be able to recover the service to within 24 hours of a disaster. This means that we should backup these objects every 24 hours:
- [ ] database of users, permissions and settings
- [ ] database of saved scenarios

**Comment by christina-moore** [comment]
Entire heroku database should now have scheduled daily backups at 02:00 BST. Need to confirm in the next few days that those are being taken.

https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduled-backups

**Comment by christina-moore** [comment]
I've confirmed the backups are being taken on `staging` and have restored one of them to check that data is available. This is a backup of the entire database so it includes user accounts, permissions, and saved scenarios as listed above.

**Comment by MichaelHanksSF** [comment]
That's great - thanks @christina-moore!
