### ISSUE TITLE
Model output: Add graph lines showing model states

### ISSUE THREAD

**Issue by MichaelHanksSF** [SocialFinanceDigitalLabs/cs-demand-model-regional#59]
Currently prediction_chart and historic_chart show only a single line representing total children per day. We would also like lines and confidence intervals for each placement type (Fostering, Residential, Supported and Other). The confidence intervals are hard to spot as they are very small (data container work should fix this) but you can zoom in on the graph to check they are displaying correctly.

Ideally each line would be as the current one, so dotted for historic and solid for the forecast, but this may not be possible if we also want a single legend for each to filter. Run any deviations in design past Michael.

Current look:
![Image](https://github.com/user-attachments/assets/cdcd1cd8-e96c-40cd-81af-8d03855fa0cd)

Find the charts in dm_regional_app/charts.py. The current chart inputs provide all the data you need for this task.

See plotly for documentation: https://plotly.com/python/line-charts/

If you run the project, you can view them on 'Historic Data' and 'Start Modelling' pages.

**Comment by WillLP-code** [comment]
completed by: https://github.com/SocialFinanceDigitalLabs/cs-demand-model-regional/pull/84
