### ISSUE TITLE
Historic graph switch to showing placement starts per day

### ISSUE THREAD

**Issue by MichaelHanksSF** [SocialFinanceDigitalLabs/cs-demand-model-regional#65]
This issue is to add another graph to the [historic_data view](https://github.com/SocialFinanceDigitalLabs/cs-demand-model-regional/blob/950289eb9feb823ad030914d8f86c5c9661aaae8/dm_regional_app/views.py#L1114) as a new chart under the existing one.

This chart would be similar to the [historic_chart](https://github.com/SocialFinanceDigitalLabs/cs-demand-model-regional/blob/950289eb9feb823ad030914d8f86c5c9661aaae8/dm_regional_app/charts.py#L264), but would show placement starts per day instead of total number of children. This measure could be got from the existing [PopulationStats.daily_entrants()](https://github.com/SocialFinanceDigitalLabs/cs-demand-model-regional/blob/950289eb9feb823ad030914d8f86c5c9661aaae8/ssda903/population_stats.py#L135).

Once the chart was present in views, it would also need to be served to the application along with the rest of the content on the page - to follow this, see how the rest is done and incorporate the new chart in the same way.

**Comment by robjharrison** [comment]
Note that 'placement starts per day' was changed by agreement to placement starts per **month** to aid/improve visualisation

**Comment by MichaelHanksSF** [comment]
[like]  Michael Hanks reacted to your message:
________________________________

**Comment by robjharrison** [comment]
Apologies i mayhave lost track of the answer to this particular question - but are the traces on this chart to also show by age_bin, or was that something that i previously added that was not actually part of the original remit on this? Adding those does clutter the plot but if they're of greater use than total counts i'm happy to re-add. For now i have made the assumption that straight counts are the preferred option.
